<?xml version="1.0" encoding="utf-8"?><!DOCTYPE context [<!ELEMENT context (device | context-attribute)*><!ELEMENT context-attribute EMPTY><!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*><!ELEMENT channel (scan-element?, attribute*)><!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY><!ELEMENT debug-attribute EMPTY><!ELEMENT buffer-attribute EMPTY><!ATTLIST context name CDATA #REQUIRED description CDATA #IMPLIED><!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED><!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED><!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED><!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED><!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED value CDATA #IMPLIED><!ATTLIST debug-attribute name CDATA #REQUIRED><!ATTLIST buffer-attribute name CDATA #REQUIRED value CDATA #IMPLIED>]><context name="xml" description="no-OS/projects/NO_OS_PROJECT NO_OS_VERSION" ><context-attribute name="fw_version" value="6b3592a6adf" /><context-attribute name="hw_carrier" value="SDP_K1" /><context-attribute name="hw_mezzanine" value="EVAL-AD3530RARDZ" /><context-attribute name="hw_name" value="EVAL-AD3530RARDZ" /><context-attribute name="uri" value="serial:/dev/ttyS0,230400,8n1n" /><context-attribute name="serial,port" value="/dev/ttyS0" /><context-attribute name="serial,description" value="ttyS0" /><device id="iio:device0" name="ad3530r"><channel id="voltage0" name="Ch0" type="output" ><scan-element index="0" format="le:u16/16>>0" /><attribute name="input_register" filename="out_voltage0_input_register" value="0" /><attribute name="raw" filename="out_voltage0_raw" value="0" /><attribute name="scale" filename="out_voltage0_scale" value="0.0381475538" /><attribute name="offset" filename="out_voltage0_offset" value="0" /><attribute name="operating_mode" filename="out_voltage0_operating_mode" value="32kOhm_to_gnd" /><attribute name="operating_mode_available" filename="out_voltage0_operating_mode_available" value="normal_operation 1kOhm_to_gnd 7k7Ohm_to_gnd 32kOhm_to_gnd" /></channel><channel id="voltage1" name="Ch1" type="output" ><scan-element index="1" format="le:u16/16>>0" /><attribute name="input_register" filename="out_voltage1_input_register" value="0" /><attribute name="raw" filename="out_voltage1_raw" value="0" /><attribute name="scale" filename="out_voltage1_scale" value="0.0381475538" /><attribute name="offset" filename="out_voltage1_offset" /><attribute name="operating_mode" filename="out_voltage1_operating_mode" value="32kOhm_to_gnd" /><attribute name="operating_mode_available" filename="out_voltage1_operating_mode_available" value="normal_operation 1kOhm_to_gnd 7k7Ohm_to_gnd 32kOhm_to_gnd" /></channel><channel id="voltage2" name="Ch2" type="output" ><scan-element index="2" format="le:u16/16>>0" /><attribute name="input_register" filename="out_voltage2_input_register" value="0" /><attribute name="raw" filename="out_voltage2_raw" value="0" /><attribute name="scale" filename="out_voltage2_scale" value="0.0381475538" /><attribute name="offset" filename="out_voltage2_offset" value="0" /><attribute name="operating_mode" filename="out_voltage2_operating_mode" value="32kOhm_to_gnd" /><attribute name="operating_mode_available" filename="out_voltage2_operating_mode_available" value="normal_operation 1kOhm_to_gnd 7k7Ohm_to_gnd 32kOhm_to_gnd" /></channel><channel id="voltage3" name="Ch3" type="output" ><scan-element index="3" format="le:u16/16>>0" /><attribute name="input_register" filename="out_voltage3_input_register" value="0" /><attribute name="raw" filename="out_voltage3_raw" value="0" /><attribute name="scale" filename="out_voltage3_scale" value="0.0381475538" /><attribute name="offset" filename="out_voltage3_offset" value="0" /><attribute name="operating_mode" filename="out_voltage3_operating_mode" value="32kOhm_to_gnd" /><attribute name="operating_mode_available" filename="out_voltage3_operating_mode_available" value="normal_operation 1kOhm_to_gnd 7k7Ohm_to_gnd 32kOhm_to_gnd" /></channel><channel id="voltage4" name="Ch4" type="output" ><scan-element index="4" format="le:u16/16>>0" /><attribute name="input_register" filename="out_voltage4_input_register" value="0" /><attribute name="raw" filename="out_voltage4_raw" value="0" /><attribute name="scale" filename="out_voltage4_scale" value="0.0381475538" /><attribute name="offset" filename="out_voltage4_offset" value="0" /><attribute name="operating_mode" filename="out_voltage4_operating_mode" value="32kOhm_to_gnd" /><attribute name="operating_mode_available" filename="out_voltage4_operating_mode_available" value="normal_operation 1kOhm_to_gnd 7k7Ohm_to_gnd 32kOhm_to_gnd" /></channel><channel id="voltage5" name="Ch5" type="output" ><scan-element index="5" format="le:u16/16>>0" /><attribute name="input_register" filename="out_voltage5_input_register" value="0" /><attribute name="raw" filename="out_voltage5_raw" value="0" /><attribute name="scale" filename="out_voltage5_scale" value="0.0381475538" /><attribute name="offset" filename="out_voltage5_offset" value="0" /><attribute name="operating_mode" filename="out_voltage5_operating_mode" value="32kOhm_to_gnd" /><attribute name="operating_mode_available" filename="out_voltage5_operating_mode_available" value="normal_operation 1kOhm_to_gnd 7k7Ohm_to_gnd 32kOhm_to_gnd" /></channel><channel id="voltage6" name="Ch6" type="output" ><scan-element index="6" format="le:u16/16>>0" /><attribute name="input_register" filename="out_voltage6_input_register" value="0" /><attribute name="raw" filename="out_voltage6_raw" value="0" /><attribute name="scale" filename="out_voltage6_scale" value="0.0381475538" /><attribute name="offset" filename="out_voltage6_offset" value="0" /><attribute name="operating_mode" filename="out_voltage6_operating_mode" value="32kOhm_to_gnd" /><attribute name="operating_mode_available" filename="out_voltage6_operating_mode_available" value="normal_operation 1kOhm_to_gnd 7k7Ohm_to_gnd 32kOhm_to_gnd" /></channel><channel id="voltage7" name="Ch7" type="output" ><scan-element index="7" format="le:u16/16>>0" /><attribute name="input_register" filename="out_voltage7_input_register" value="0" /><attribute name="raw" filename="out_voltage7_raw" value="0" /><attribute name="scale" filename="out_voltage7_scale" value="0.0381475538" /><attribute name="offset" filename="out_voltage7_offset" value="0" /><attribute name="operating_mode" filename="out_voltage7_operating_mode" value="32kOhm_to_gnd" /><attribute name="operating_mode_available" filename="out_voltage7_operating_mode_available" value="normal_operation 1kOhm_to_gnd 7k7Ohm_to_gnd 32kOhm_to_gnd" /></channel><attribute name="reference_select" value="external_ref" /><attribute name="reference_select_available" value="external_ref internal_ref" /><attribute name="range" value="0_to_VREF" /><attribute name="range_available" value="0_to_VREF 0_to_2VREF" /><attribute name="mux_out_select" value="powered_down" /><attribute name="mux_out_select_available" value="powered_down VOUT0 IOUT0_source IOUT0_sink VOUT1 IOUT1_source IOUT1_sink VOUT2 IOUT2_source IOUT2_sink VOUT3 IOUT3_source IOUT3_sink VOUT4 IOUT4_source IOUT4_sink VOUT5 IOUT5_source IOUT5_sink VOUT6 IOUT6_source IOUT6_sink VOUT7 IOUT7_source IOUT7_sink" /><attribute name="all_ch_operating_mode" value="32kOhm_to_gnd" /><attribute name="all_ch_operating_mode_available" value="normal_operation 1kOhm_to_gnd 7k7Ohm_to_gnd 32kOhm_to_gnd" /><attribute name="all_ch_input_registers" value="0" /><attribute name="all_ch_raw" value="0" /><attribute name="sampling_frequency" value="562746" /><attribute name="sw_ldac_trigger" value="ldac_trigger" /><attribute name="sw_ldac_trigger_available" value="ldac_trigger" /><attribute name="hw_ldac_trigger" value="ldac_trigger" /><attribute name="hw_ldac_trigger_available" value="ldac_trigger" /><debug-attribute name="direct_reg_access" /></device></context>